---
- hosts: dev,prod
  user: ec2-user
  become: yes
  become_method: sudo
  tasks:
  - name: upgrade all packages
    yum:
      name: '*'
      state: latest
  - name: install Apache
    yum:
      name: httpd
      state: present
  - name: apache owner
    file:
      path: /var/www/html/
      mode: u=rwX,g=rX,o=rX
      recurse: yes
      owner: ec2-user
      group: ec2-user
  - name: Make sure Apache is started now and at boot
    service: name=httpd state=started enabled=yes

