variable "aws_region" {}
variable "aws_credentials" {}
variable "aws_profile" {}
variable "vpc_cidr" {}
variable "localip" {}
variable "key_name" {}
variable "public_key_path" {}
variable "all_instance_type" {}
variable "all_ami" {}
